model_list:
  - model_name: os.environ/MODEL_NAME_1 # Model Alias to use for requests
    litellm_params:
      model: os.environ/GROUQ_MODEL_NAME_1
      api_key: os.environ/GROUQ_API_KEY_ACCOUNT_1
      
  - model_name: os.environ/MODEL_NAME_1
    litellm_params:
      model: os.environ/GROUQ_MODEL_NAME_1
      api_key: os.environ/GROUQ_API_KEY_ACCOUNT_2

  - model_name: os.environ/MODEL_NAME_1
    litellm_params:
      model: os.environ/GROUQ_MODEL_NAME_1
      api_key: os.environ/GROUQ_API_KEY_ACCOUNT_3

  - model_name: os.environ/MODEL_NAME_1
    litellm_params:
      model: os.environ/GROUQ_MODEL_NAME_1
      api_key: os.environ/GROUQ_API_KEY_ACCOUNT_4

  - model_name: os.environ/MODEL_NAME_1
    litellm_params:
      model: os.environ/GROUQ_MODEL_NAME_1
      api_key: os.environ/GROUQ_API_KEY_ACCOUNT_5

  - model_name: os.environ/MODEL_NAME_2 # Model Alias to use for requests
    litellm_params:
      model: os.environ/GROUQ_MODEL_NAME_2
      api_key: os.environ/GROUQ_API_KEY_ACCOUNT_1

  - model_name: os.environ/MODEL_NAME_2
    litellm_params:
      model: os.environ/GROUQ_MODEL_NAME_2
      api_key: os.environ/GROUQ_API_KEY_ACCOUNT_2

  - model_name: os.environ/MODEL_NAME_2
    litellm_params:
      model: os.environ/GROUQ_MODEL_NAME_2
      api_key: os.environ/GROUQ_API_KEY_ACCOUNT_3

  - model_name: os.environ/MODEL_NAME_2
    litellm_params:
      model: os.environ/GROUQ_MODEL_NAME_2
      api_key: os.environ/GROUQ_API_KEY_ACCOUNT_4

  - model_name: os.environ/MODEL_NAME_2
    litellm_params:
      model: os.environ/GROUQ_MODEL_NAME_2
      api_key: os.environ/GROUQ_API_KEY_ACCOUNT_5

  - model_name: os.environ/MODEL_NAME_3
    litellm_params:
      model: os.environ/OPENAI_MODEL_NAME_3
      api_key: os.environ/OPENAI_API_KEY

  - model_name: os.environ/MODEL_NAME_4
    litellm_params:
      model: os.environ/OPENAI_MODEL_NAME_4
      api_key: os.environ/OPENAI_API_KEY
  
  - model_name: os.environ/MODEL_NAME_5
    litellm_params:
      model: os.environ/OPENAI_MODEL_NAME_5
      api_key: os.environ/OPENAI_API_KEY

  - model_name: os.environ/MODEL_NAME_6
    litellm_params:
      model: os.environ/OPENAI_MODEL_NAME_6
      api_key: os.environ/OPENAI_API_KEY

  - model_name: os.environ/MODEL_NAME_7
    litellm_params:
      model: os.environ/OPENAI_MODEL_NAME_7
      api_key: os.environ/OPENAI_API_KEY

  - model_name: os.environ/MODEL_NAME_8
    litellm_params:
      model: os.environ/OPENAI_MODEL_NAME_8
      api_key: os.environ/OPENAI_API_KEY

  - model_name: os.environ/MODEL_NAME_9
    litellm_params:
      model: os.environ/OPENAI_MODEL_NAME_9
      api_key: os.environ/OPENAI_API_KEY

  - model_name: os.environ/MODEL_NAME_10
    litellm_params:
      model: os.environ/OPENAI_MODEL_NAME_10
      api_key: os.environ/OPENAI_API_KEY

  - model_name: os.environ/MODEL_NAME_11
    litellm_params:
      model: os.environ/OPENAI_MODEL_NAME_11
      api_key: os.environ/OPENAI_API_KEY

  - model_name: os.environ/MODEL_NAME_12
    litellm_params:
      model: os.environ/OPENAI_MODEL_NAME_12
      api_key: os.environ/OPENAI_API_KEY