services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ${HOME}/app/backend/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ./entrypoint.sh
    restart: unless-stopped